devsummit/backend

- README.md
- alembic.ini
- migrations/README
- migrations/env.py
- migrations/script.py.mako
- migrations/versions/1314685ec5c0_create_user_table.py
- migrations/versions/62832c972212_create_user_role_table.py
- migrations/versions/aebf5ba482d6_create_role_table.py
> 13 setup database and user

- app/__init__.py
- app/configs/settings.py
- app/controllers/base_controller.py
- app/controllers/user_authorization_controller.py
- app/models/__init__.py
- app/models/access_token.py
- app/models/base_model.py
- app/models/user.py
- app/routes/auth.py
- migrations/versions/79d78e481ff5_create_access_token_table.py
> 12 user login

- Makefile
> #23 change python version in virtual env

- app/middlewares/authentication.py
- app/routes/api.py
- app/routes/auth.py
> 25 add auth middleware

- migrations/versions/05cb70b1d87c_create_order_table.py
- migrations/versions/7df08705de21_create_order_details_table.py
- migrations/versions/f8e18fbe2d41_create_tickets_table.py
> #29 add all order migrations

- migrations/versions/48e1845a4774_create_table_beacons.py
- migrations/versions/c160958b84a7_create_table_stage_photos.py
- migrations/versions/cf5c0ef7ceaa_create_table_spots.py
- migrations/versions/efa23ae7975d_create_table_stages.py
> stage table migrations

- apiary.apib
> 40 apiary user type

- apiary.apib
> 41 apiary event related

- apiary.apib
> 44 apiary transaction

- apiary.apib
- dredd.yml
- orders.apib
> add orders apiary

- migrations/versions/0db2d38988c5_create_schedules_table.py
- migrations/versions/3ae3a27a9771_create_point_transaction_log_table.py
- migrations/versions/4e5eaa7314eb_create_events_table.py
- migrations/versions/55d9b9bc9d9c_create_ticket_transfer_log_table.py
- migrations/versions/6467a01dbe80_create_materials_table.py
- migrations/versions/6cdc598b190b_create_user_ticket_table.py
- migrations/versions/8ba67ec99bcb_create_attendees_table.py
- migrations/versions/ae1088ec2272_create_booths_table.py
- migrations/versions/b1cb653806ab_create_user_photo_table.py
- migrations/versions/dbfc685633f9_create_speakers_table.py
#54  Fix
Finish all the missing migrations.
> #54 finish all migration tables

- README.md
- app/controllers/base_controller.py
- app/models/role.py
- manage.py
- migrations/versions/6467a01dbe80_create_materials_table.py
- migrations/versions/8ba67ec99bcb_create_attendees_table.py
- seeders/role_seeder.py
- seeders/seed.py
> 53 create role seeder

- app/controllers/stage_controller.py
- app/models/stage.py
- app/routes/api.py
- app/services/__init__.py
- app/services/stage_service.py
> 49 api stage

- app/controllers/beacon_controller.py
- app/models/beacon.py
- app/routes/api.py
- app/services/__init__.py
- app/services/beacon_service.py
> 48 api beacon

- app/controllers/spot_controller.py
- app/models/spot.py
- app/routes/api.py
- app/services/__init__.py
- app/services/spot_service.py
> 50 api spot

- migrations/versions/dbfc685633f9_create_speakers_table.py
> modify speaker migration to add new columns

- migrations/versions/4e5eaa7314eb_create_events_table.py
> Add title to table events #64

- app/controllers/schedule_controller.py
- app/models/event.py
- app/models/events.py
- app/models/schedule.py
- app/routes/api.py
- app/services/__init__.py
- app/services/event_service.py
- app/services/schedule_service.py
- migrations/versions/0db2d38988c5_create_schedules_table.py
- migrations/versions/4e5eaa7314eb_create_events_table.py
- seeders/events_seeder.py
> 52 api schedule

- app/configs/constants.py
- app/services/__init__.py
- app/services/user_service.py
> 14 registration as x

- app/services/user_service.py
> add payload validation

- blueprint/data/material.apib
- blueprint/data/speaker.apib
- blueprint/data/stage.apib
- blueprint/data/ticket.apib
- blueprint/data/user.apib
- blueprint/stage.apib
- blueprint/user.apib
> 96 apiary fix

- app/services/user_service.py
> 100 auth register failed to register but data still inserted

- app/services/user_service.py
- migrations/versions/c160958b84a7_create_table_stage_photos.py
> 90 bug migrations stages photos

- app/controllers/user_authorization_controller.py
- app/routes/auth.py
- app/services/user_service.py
> 86 api users change user detail

- app/models/access_token.py
- app/services/user_service.py
- requirements.txt
- seeders/clients_seeder.py
- seeders/seed.py
#106 
Add clients seeder for
Other
> 106 client seeder

- app/controllers/user_authorization_controller.py
> #110 add included data

- app/controllers/user_ticket_controller.py
- app/routes/api.py
- app/services/__init__.py
- app/services/user_ticket_service.py
> 108 api user ticket

- migrations/versions/79d78e481ff5_create_access_token_table.py
- migrations/versions/d0f006ed40b0_create_newsletters_table.py
- migrations/versions/e431e5b0f9c3_create_client_table.py
> #111 add client id column

- app/controllers/attendee_controller.py
- app/routes/api.py
- app/services/__init__.py
- app/services/attendee_service.py
> 109 api attendee

- app/controllers/user_authorization_controller.py
- app/services/user_service.py
> 110 include user data on logged in

- app/controllers/attendee_controller.py
- app/routes/api.py
- app/services/attendee_service.py
> 118 include user to attendees api respond

- app/controllers/user_authorization_controller.py
- app/models/access_token.py
- app/routes/auth.py
- app/services/user_service.py
> 113 refresh token api

- app/services/user_service.py
> 121 bug google signin

- app/controllers/user_authorization_controller.py
- app/services/user_service.py
> #128 handle no user social registration

- app/controllers/user_authorization_controller.py
- app/services/user_service.py
> 68 register with phone number

- app/controllers/user_authorization_controller.py
- app/services/user_service.py
- seeders/clients_seeder.py
> Fix bug indentation and fix mobile login api

- app/controllers/user_authorization_controller.py
- app/services/user_service.py
> 139 auth handler

- app/controllers/main_controller.py
- app/templates/admin/attendees/attendee_detail.html
- app/templates/admin/attendees/attendees.html
> 143 attendee modal detail

- app/controllers/order_controller.py
- app/controllers/payment_controller.py
- app/controllers/user_authorization_controller.py
- app/routes/api.py
- app/routes/main.py
- app/services/booth_service.py
- app/services/payment_service.py
> 147 paymentlist

- app/controllers/payment_controller.py
- app/routes/api.py
- app/services/payment_service.py
> Credit card payment

- app/controllers/order_details_controller.py
- app/services/order_details_service.py
> 152 orderdetails tweak

- seeders/order_details_seeder.py
- seeders/seed.py
> 154 order details seeder

- app/models/user_ticket.py
- migrations/versions/6cdc598b190b_create_user_tickets_table.py
- migrations/versions/f8e18fbe2d41_create_tickets_table.py
- seeders/user_tickets_seeder.py
> 157 list paid tickets

- app/controllers/order_details_controller.py
- app/controllers/payment_controller.py
- app/controllers/user_authorization_controller.py
- app/services/payment_service.py
- seeders/order_details_seeder.py
- seeders/seed.py
> 159 tweak payment

- app/controllers/main_controller.py
- app/models/user.py
- app/routes/main.py
- app/static/assets/dist/js/auth.js
- app/templates/admin/base/index.html
- app/templates/admin/tickets/ticket_add.html
- app/templates/admin/tickets/ticket_delete.html
- app/templates/admin/tickets/ticket_edit.html
- app/templates/admin/tickets/tickets.html
> 156 admin ticket management

- app/controllers/user_authorization_controller.py
- app/services/user_service.py
> #172 provide more data to auth error handling

- app/models/user.py
- app/routes/main.py
- app/services/payment_service.py
- main.py
- seeders/tickets_seeder.py
> #177 change ticket seeder

- app/controllers/order_controller.py
- app/controllers/order_details_controller.py
- app/controllers/referal_controller.py
- app/controllers/user_ticket_controller.py
- app/models/check_in.py
- app/models/order.py
- app/models/referal.py
- app/models/user_ticket.py
- app/routes/api.py
- app/services/__init__.py
- app/services/order_details_service.py
- app/services/order_service.py
- app/services/payment_service.py
- app/services/referal_service.py
- app/services/user_ticket_service.py
- migrations/versions/05cb70b1d87c_create_order_table.py
- migrations/versions/6cdc598b190b_create_user_tickets_table.py
- migrations/versions/f40fd4fc554d_create_referal_table.py
- migrations/versions/f66e7f85d4e7_create_checkins_table.py
- seeders/user_tickets_seeder.py
> 173 api referal code

- app/controllers/user_authorization_controller.py
- app/templates/admin/auth/login.html
> #167 add role checking to admin login

- app/controllers/booth_controller.py
- app/controllers/main_controller.py
- app/routes/api.py
- app/routes/main.py
- app/services/booth_service.py
- app/templates/admin/base/index.html
- app/templates/admin/booths/booth_edit.html
- app/templates/admin/booths/booths.html
> 170 admin booth management

- app/controllers/schedule_controller.py
- app/models/event.py
- app/models/schedule.py
- app/routes/api.py
- app/services/schedule_service.py
- migrations/versions/4e5eaa7314eb_create_events_table.py
- seeders/events_seeder.py
> 190 schedule change spec

- app/controllers/main_controller.py
- app/routes/main.py
- app/templates/admin/base/index.html
- app/templates/admin/speakers/speaker_edit.html
- app/templates/admin/speakers/speakers.html
> Add admin speaker management

- app/configs/constants.py
- app/controllers/ticket_controller.py
- app/services/ticket_service.py
- seeders/tickets_seeder.py
> 188 ticket count

- app/controllers/payment_controller.py
- app/routes/api.py
- app/services/payment_service.py
> 187 credit challenge

- app/controllers/main_controller.py
- app/routes/main.py
- app/services/payment_service.py
- app/services/schedule_service.py
- app/templates/admin/events/schedules/schedule_add.html
- app/templates/admin/events/schedules/schedule_delete.html
- app/templates/admin/events/schedules/schedule_edit.html
- app/templates/admin/events/schedules/schedules.html
> 204 include stage to schedule

- app/configs/settings.py
- app/templates/admin/accounts/account_edit.html
- app/templates/admin/accounts/accounts.html
- app/templates/admin/base/modal_delete.html
- migrations/env.py
> 211 bug admin panel account management

- app/controllers/booth_controller.py
- app/services/booth_service.py
- app/templates/admin/booths/booth_edit.html
- app/templates/admin/booths/booths.html
> Fix admin panel booth list

- app/controllers/booth_controller.py
- app/controllers/user_controller.py
- app/services/booth_service.py
- app/templates/admin/accounts/account_edit.html
- app/templates/admin/accounts/accounts.html
- app/templates/admin/attendees/attendees.html
- app/templates/admin/base/modal_delete.html
- app/templates/admin/booths/booth_edit.html
- app/templates/admin/booths/booths.html
- app/templates/admin/events/events.html
- app/templates/admin/events/events_delete.html
- app/templates/admin/events/events_edit.html
- app/templates/admin/events/schedules/schedule_delete.html
- app/templates/admin/events/schedules/schedule_edit.html
- app/templates/admin/events/schedules/schedules.html
- app/templates/admin/payments/payments.html
- app/templates/admin/referals/referal_delete.html
- app/templates/admin/referals/referal_edit.html
- app/templates/admin/referals/referals.html
- app/templates/admin/speakers/speaker_edit.html
- app/templates/admin/speakers/speakers.html
- app/templates/admin/stages/stage_edit.html
- app/templates/admin/stages/stages.html
- app/templates/admin/tickets/ticket_delete.html
- app/templates/admin/tickets/ticket_edit.html
- app/templates/admin/tickets/tickets.html
> 215 clean up admin page

- app/controllers/payment_controller.py
- app/services/payment_service.py
> 171 payment error handling

- app/builders/response_builder.py
- app/controllers/attendee_controller.py
- app/controllers/booth_controller.py
- app/controllers/event_controller.py
- app/controllers/payment_controller.py
- app/controllers/user_controller.py
- app/routes/api.py
- app/services/__init__.py
- app/services/attendee_service.py
- app/services/base_service.py
- app/services/booth_service.py
- app/services/event_service.py
- app/services/order_service.py
- app/services/payment_service.py
- app/services/user_service.py
- seeders/order_details_seeder.py
- seeders/orders_seeder.py
- seeders/payments_seeder.py
- seeders/user_tickets_seeder.py
> 225 api pagination

- app/controllers/attendee_controller.py
- app/controllers/main_controller.py
- app/services/attendee_service.py
- app/services/base_service.py
- app/services/booth_service.py
- app/services/user_service.py
> 236 fix paginate bug

- app/configs/settings.py
- app/controllers/main_controller.py
- app/controllers/partner_controller.py
- app/controllers/speaker_controller.py
- app/models/partners.py
- app/routes/api.py
- app/routes/main.py
- app/services/__init__.py
- app/services/event_service.py
- app/services/helper.py
- app/services/partner_service.py
- app/static/assets/dist/js/auth.js
- app/static/constants.js
- app/templates/admin/partners/partner_add.html
- app/templates/admin/partners/partner_edit.html
- app/templates/admin/partners/partners.html
- migrations/versions/4a836f32b170_create_partners_table.py
> 233 entry partner

- app/controllers/entry_cash_log_controller.py
- app/services/entry_cash_log_service.py
- app/static/constants.js
- app/templates/admin/accounts/account_edit.html
- app/templates/admin/auth/login.html
- app/templates/admin/base/index.html
- app/templates/admin/entrycash/entrycash.html
- app/templates/admin/entrycash/entrycash_add.html
- app/templates/admin/entrycash/entrycash_edit.html
- app/templates/admin/events/schedules/schedules.html
- app/templates/admin/partners/partners.html
- app/templates/admin/payments/authorize-modal.html
- app/templates/admin/payments/payments.html
- app/templates/admin/referals/referal_delete.html
- app/templates/admin/referals/referal_edit.html
- app/templates/admin/stages/stage_edit.html
- app/templates/admin/tickets/ticket_edit.html
- migrations/versions/ae0efd1cf5c1_create_entry_cash.py
- seeders/seed.py
> 235 admin panel entry cash

- app/controllers/payment_controller.py
- app/services/payment_service.py
> 232 tweak indomaret payment

- app/builders/response_builder.py
- app/controllers/main_controller.py
- app/controllers/payment_controller.py
- app/routes/main.py
- app/static/assets/dist/js/auth.js
- app/templates/admin/base/index.html
- app/templates/admin/events/events_add.html
- app/templates/admin/users/changepassword.html
> 252 fix bugs

- app/controllers/speaker_document_controller.py
- app/routes/api.py
- app/templates/admin/speakers/speaker_document.html
- app/templates/admin/speakers/speakers.html
> add speaker upload material

- app/controllers/payment_controller.py
- app/services/payment_service.py
- migrations/versions/82e92967c0cd_create_payment_table.py
> 258 clean payment bug

- app/routes/api.py
- app/services/schedule_service.py
> add filter day for schedules

- app/configs/constants.py
- app/controllers/payment_controller.py
- app/models/payment.py
- app/services/payment_service.py
- migrations/versions/82e92967c0cd_create_payment_table.py
> Transfer payment add va field

- app/controllers/user_authorization_controller.py
- app/models/user.py
- app/services/base_service.py
- app/services/user_service.py
> 266 include role and default photo

- app/controllers/main_controller.py
- app/models/rundown_list.py
- app/routes/api.py
- app/routes/main.py
- app/services/payment_service.py
- app/services/rundown_list_service.py
- app/templates/admin/payments/authorize-modal.html
- app/templates/admin/payments/authorize-needed.html
- migrations/versions/63cc8631a13f_create_rundown_lists.py
> 269 bug authorization

- app/models/payment.py
- app/services/base_service.py
- app/services/payment_service.py
- app/services/user_photo_service.py
- migrations/versions/82e92967c0cd_create_payment_table.py
> 271 payment expiry

- app/controllers/speaker_document_controller.py
- app/models/speaker_document.py
- app/services/speaker_document_service.py
- migrations/versions/6467a01dbe80_create_materials_table.py
> Response document

- app/controllers/user_controller.py
- app/models/rundown_list.py
- app/routes/main.py
- app/services/rundown_list_service.py
- app/services/user_service.py
- app/templates/admin/accounts/account_input.html
- migrations/versions/63cc8631a13f_create_rundown_lists.py
#265  Fix
with @hafizhanindito
> 265 bug admin panel add new account not working

- app/configs/constants.py
- app/controllers/payment_controller.py
- app/controllers/user_photo_controller.py
- app/routes/api.py
- app/services/payment_service.py
> 273 bug internet banking payments

- app/controllers/user_authorization_controller.py
- app/models/user.py
- app/services/user_service.py
- app/services/user_ticket_service.py
- migrations/versions/1314685ec5c0_create_user_table.py
- migrations/versions/caa004f8af83_add_referer_column_user_table.py
- seeders/order_details_seeder.py
- seeders/payments_seeder.py
- seeders/role_seeder.py
> 280 tweak registration

- app/controllers/booth_controller.py
- app/models/booth.py
- app/services/booth_service.py
- migrations/versions/caa004f8af83_add_referer_column_user_table.py
> 289 tweak booth

- app/controllers/user_authorization_controller.py
- app/services/user_service.py
> Hotfix register

- app/services/user_service.py
> #297 check user email as username while login

- app/controllers/entry_cash_log_controller.py
- app/controllers/source_controller.py
- app/models/entry_cash_log.py
- app/models/source.py
- app/routes/api.py
- app/services/__init__.py
- app/services/entry_cash_log_service.py
- app/services/source_service.py
- app/templates/admin/base/index.html
- app/templates/admin/entrycash/entrycash.html
- app/templates/admin/entrycash/entrycash_add.html
- app/templates/admin/entrycash/entrycash_edit.html
- migrations/versions/3ff8278518a6_create_sources_table.py
- migrations/versions/540bd35ba67d_edit_entry_cash_log_table.py
> 281 admin panel finance

- app/controllers/speaker_document_controller.py
- app/models/speaker_document.py
- app/routes/api.py
- app/services/speaker_document_service.py
- app/templates/admin/speakers/speaker_document.html
- migrations/versions/4a97ebacb049_edit_materials_table.py
> 293 flag material

- app/services/schedule_service.py
- app/services/speaker_document_service.py
> 308 tweak schedule response

- app/templates/admin/attendees/attendees.html
- app/templates/admin/partnership/partners/partners.html
> 306 Admin Page - Display Image

- manage.py
- seeders/production_seed.py
> 310 clean up seeders

- app/controllers/redeem_code_controller.py
- app/controllers/user_controller.py
- app/models/redeem_code.py
- app/routes/api.py
- app/services/redeem_code_service.py
- app/services/user_service.py
- app/templates/admin/redeem_codes/redeem_codes.html
- migrations/versions/0f1eecdee15c_merge_head_edit_redeem_code_table.py
> 301 redeem 

- app/controllers/Grantrole_controller.py
- app/controllers/user_controller.py
- app/models/speaker.py
- app/services/grantrole_service.py
- app/services/user_service.py
- app/static/constants.js
- app/templates/admin/accounts/account_grant.html
- app/templates/admin/accounts/account_input.html
- app/templates/admin/accounts/accounts.html
- app/templates/admin/accounts/grant/speaker_grant.html
- app/templates/admin/accounts/speaker.html
> 311 add speaker type

- migrations/versions/3967d0f62652_add_type_to_speaker.py
> #301 add new speaker field

- app/services/redeem_code_service.py
> #301 add userticket on redeemcode accepted

- app/controllers/entry_cash_log_controller.py
- app/routes/api.py
- app/services/entry_cash_log_service.py
> Add entry cash log filter api

- app/services/booth_service.py
> Fix update logo response url

- app/configs/constants.py
- app/controllers/admin_controller.py
- app/controllers/user_authorization_controller.py
- app/models/user.py
- app/routes/api.py
- app/routes/auth.py
- app/services/__init__.py
- app/services/fcm_service.py
- app/services/notification_service.py
- app/services/user_service.py
- migrations/versions/8034c678fd2d_add_fcm_token.py
> 316 fcm notification

- app/services/booth_service.py
> 327 use helper_url to make image accessible

- app/routes/main.py
- app/templates/admin/base/index.html
- app/templates/admin/communication/notification.html
- app/templates/admin/communication/post.html
- app/templates/admin/tickets/ticket_add.html
> 330 communication admin

- app/routes/api.py
- app/routes/main.py
- app/templates/admin/base/index.html
- app/templates/admin/communication/notification.html
- app/templates/admin/communication/post.html
- app/templates/admin/speakers/speaker_candidate_modal.html
- app/templates/admin/speakers/speaker_candidates.html
- app/templates/admin/tickets/ticket_add.html
> 341 bug speaker prospect

- app/services/fcm_service.py
- app/services/user_service.py
> 339 tweak registration

- app/controllers/redeem_code_controller.py
- app/routes/api.py
- app/services/redeem_code_service.py
- app/templates/admin/redeem_codes/redeem_codes.html
- app/templates/admin/redeem_codes/redeem_codes_detail.html
> 343 tweak redeem code

- app/__init__.py
- app/configs/settings.py
- app/controllers/admin_controller.py
- app/models/__init__.py
- app/models/feed.py
- app/routes/api.py
- app/services/email_service.py
- app/services/fcm_service.py
- app/templates/admin/base/modal_email.html
- app/templates/admin/partnership/partners/partners.html
- requirements.txt
> 345 email client

- app/controllers/main_controller.py
- app/controllers/source_controller.py
- app/routes/main.py
- app/templates/admin/base/index.html
- app/templates/admin/sources/source.html
- app/templates/admin/sources/source_add.html
- app/templates/admin/sources/source_edit.html
> 349 admin panel sources

- app/configs/settings.py
> fix setting

- app/models/user.py
- app/templates/admin/speakers/speakers.html
> Add speaker type

- app/controllers/Grantrole_controller.py
- app/services/grantrole_service.py
- app/templates/admin/accounts/account_grant.html
- app/templates/admin/accounts/accounts.html
> #283 fix grant role bug

- app/services/redeem_code_service.py
- app/templates/admin/redeem_codes/redeem_codes.html
- app/templates/admin/redeem_codes/redeem_codes_detail.html
> Group redeem codes

- app/templates/admin/accounts/account_input.html
- app/templates/admin/accounts/accounts.html
- app/templates/admin/accounts/booth.html
> Tweak admin panel

- app/configs/constants.py
- app/controllers/main_controller.py
- app/middlewares/rbac.py
- app/routes/main.py
- app/services/helper.py
- app/static/assets/dist/js/auth.js
- app/templates/admin/base/404.html
- app/templates/admin/base/index.html
- app/templates/admin/partnership/partners/partners.html
check it, it's not good but ok lah
> Basic role base access control

- app/controllers/feed_controller.py
- app/routes/api.py
- app/services/feed_service.py
> #340 attempt-1 fix through getting page parameter from route level

- app/controllers/Grantrole_controller.py
- app/models/booth.py
- app/services/grantrole_service.py
- app/services/user_service.py
- app/templates/admin/accounts/account_grant.html
- app/templates/admin/accounts/account_input.html
- app/templates/admin/accounts/grant/booth_grant.html
> Admin panel booth tweak

- app/templates/admin/base/index.html
> temp fix for auth control menu hide

- app/configs/constants.py
- app/controllers/user_controller.py
- app/services/base_service.py
- app/services/user_service.py
- app/templates/admin/accounts/account_input.html
> #368 fix edit user bug

- app/services/payment_service.py
> #371 save redirect payment url in va_number field

- app/controllers/main_controller.py
- app/templates/admin/entrycash/entrycash_add.html
- app/templates/admin/entrycash/entrycash_edit.html
> #374 entry cash log

- app/controllers/redeem_code_controller.py
- app/models/user_ticket.py
- app/routes/api.py
- app/services/redeem_code_service.py
- app/services/user_service.py
- migrations/versions/f4cc2d8278b3_create_code_field_for_user_ticket.py
> 380 ticket code

- app/routes/api.py
- app/static/assets/dist/js/auth.js
- app/templates/admin/base/index.html
> #377 display user photo - admin panel

- app/controllers/main_controller.py
- app/services/__init__.py
- app/services/overview_service.py
- app/templates/admin/base/index.html
- app/templates/admin/base/overview.html
> Dashboard overview

- app/static/constants.js
- app/templates/admin/accounts/accounts.html
#370 
- add code for get the speaker type and stage
> add code for get the speaker type and stage

- app/controllers/feed_controller.py
- app/routes/api.py
- app/services/feed_service.py
> #390 add delete feed post

- app/controllers/ticket_transfer_controller.py
- app/routes/api.py
- app/services/ticket_transfer_service.py
> Wip tweaking ticket transfer

- app/controllers/redeem_code_controller.py
- app/services/redeem_code_service.py
> #393 tweak redeem code response similar to login

- app/models/redeem_code.py
- app/services/redeem_code_service.py
- app/templates/admin/redeem_codes/redeem_codes.html
- migrations/versions/4bb2073a8f01_drop_unique_column_code_redeem_codes.py
- migrations/versions/ab469fe11442_edit_redeem_codes_table.py
> 383 redeem code to short

- app/models/entry_cash_log.py
- migrations/versions/5cb51ff416bc_edit_entry_cash_debit_credit_data_type.py
> 385 Change Entry_Cash_Log fields type

- app/controllers/feed_report_controller.py
- app/models/feed_report.py
- app/routes/api.py
- app/services/__init__.py
- app/services/feed_report_service.py
- migrations/versions/3e0424b67645_add_feed_report_migration.py
#389
As user I should be able to report certain post to prevent the feed list to be filled with unwanted stuff.
add the report system by saving the following items:
-  [x] type
> 389 feed report api

- app/services/user_service.py
> #388 fix referral bug for non user role

- app/middlewares/authentication.py
> #401 put extra check in token required

- app/controllers/user_authorization_controller.py
- app/controllers/user_controller.py
- app/routes/auth.py
- app/services/user_service.py
#378 
- expose authorize user endpoint
> 378 expose authorize user endpoint

- app/controllers/feed_report_controller.py
> #400 Bug report-feed

- app/configs/constants.py
- app/controllers/points_controller.py
- app/models/point_transaction_log.py
- app/models/user.py
- app/services/points_transaction_service.py
- app/templates/admin/base/index.html
- migrations/versions/9171ee250063_move_points_to_user.py
- migrations/versions/b1dfd323d88f_change_attendee_id_to_user_id_transfer_.py
- seeders/users_seeder.py
> 405 refactor attendee

- app/services/overview_service.py
> tweak overview dahsboard

- app/controllers/feed_controller.py
> remove message validation

- app/configs/constants.py
- app/services/feed_service.py
- requirements.txt
> resize feed photo

- app/services/entry_cash_log_service.py
- app/templates/admin/entrycash/entrycash.html
- app/templates/admin/entrycash/entrycash_add.html
- app/templates/admin/entrycash/entrycash_edit.html
#413 
Change format and add empty checker for debit and credit value of cashlog
[x] Cashlog List
[x] Report
> 413 format currency

- app/controllers/feed_controller.py
- app/models/feed.py
- app/services/base_service.py
- app/services/feed_service.py
- migrations/versions/0871ffb7defd_add_type_and_redirec_url_in_feeds_table.py
#416
- [x ] add field type, redirect_url, sponsor_id
> 416 tweak feed sponsor

- app/controllers/sponsor_template_controller.py
- app/models/sponsor_templates.py
- app/routes/api.py
- app/services/__init__.py
- app/services/sponsor_service.py
- app/services/sponsor_template_service.py
- migrations/versions/b9dc4f84ae83_create_sponsor_templates_table.py
> 410 sponsor feed templates

- app/configs/settings.py
- app/controllers/prize_list_controller.py
- app/models/prize_list.py
- app/routes/api.py
- app/services/__init__.py
- app/services/base_service.py
- app/services/prize_list_service.py
- migrations/versions/90062c172360_create_prize_lists_table.py
> #420 Prizing 

- app/controllers/main_controller.py
- app/controllers/sponsor_template_controller.py
- app/models/sponsor_templates.py
- app/routes/api.py
- app/routes/main.py
- app/services/sponsor_template_service.py
- app/templates/admin/base/index.html
- app/templates/admin/sponsor_template/sponsor_template.html
- app/templates/admin/sponsor_template/sponsor_template_edit.html
> 419 admin panel sponsor feed template

- app/controllers/schedule_controller.py
- app/models/panel_event.py
- app/services/base_service.py
- app/services/event_service.py
- app/services/schedule_service.py
- migrations/versions/7825659604b1_create_panel_event_table.py
> add support for panel speaker

- app/controllers/feed_controller.py
- app/controllers/main_controller.py
- app/routes/main.py
- app/services/feed_service.py
- app/services/sponsor_template_service.py
- app/templates/admin/base/index.html
- app/templates/admin/communication/post.html
- app/templates/admin/communication/sponsor_post.html
> 423 admin add post sponsor feed

- app/controllers/partner_controller.py
- app/routes/api.py
- app/services/partner_service.py
> 429 filter partner

- app/static/assets/dist/css/select2.css
- app/static/assets/dist/js/select2.js
- app/templates/admin/events/events_add.html
> #425 choose multiple speaker

- app/controllers/Grantrole_controller.py
- app/controllers/booth_controller.py
- app/models/booth.py
- app/services/booth_service.py
- app/services/grantrole_service.py
- app/templates/admin/accounts/account_grant.html
- app/templates/admin/accounts/accounts.html
- app/templates/admin/accounts/booth.html
- app/templates/admin/accounts/grant/booth_grant.html
- app/templates/admin/booths/booth_edit.html
- app/templates/admin/booths/booths.html
- migrations/versions/063911936966_add_name_booth_table.py
> 434 add booth name

- app/controllers/package_management_controller.py
- app/models/package_management.py
- app/routes/api.py
- app/services/__init__.py
- app/services/package_management_service.py
- migrations/versions/f962a2941f5b_create_packages_management_table.py
- requirements.txt
> #436 add migration, model, and CRUD API for package management

- app/controllers/main_controller.py
- app/routes/main.py
- app/templates/admin/base/index.html
- app/templates/admin/partnership/packages/package_add.html
- app/templates/admin/partnership/packages/package_edit.html
- app/templates/admin/partnership/packages/packages.html
> 437 admin package management

- app/controllers/booth_controller.py
- app/controllers/main_controller.py
- app/controllers/package_management_controller.py
- app/models/booth.py
- app/routes/api.py
- app/routes/main.py
- app/services/booth_service.py
- app/services/redeem_code_service.py
- app/templates/admin/base/index.html
- app/templates/admin/booths/booths.html
- app/templates/admin/partnership/packages/package_purchase/package_purchase.html
- app/templates/admin/partnership/packages/package_purchase/package_purchase_add.html
> 443 package purchase menu

- app/templates/admin/entrycash/entrycash.html
- app/templates/admin/entrycash/entrycash_add.html
- app/templates/admin/entrycash/entrycash_edit.html
> add and edit entry cash checker

- app/configs/constants.py
> #449 fix bug ambassador role

- app/models/feed.py
- app/services/feed_report_service.py
- app/templates/admin/feed_reports/feed_reports.html
- app/templates/admin/feed_reports/feed_reports_ban.html
> Ban feed admin

- app/controllers/ticket_transfer_controller.py
- app/models/ticket_transfer_log.py
- app/services/ticket_transfer_service.py
> #453 api ticket transfer

- app/controllers/main_controller.py
- app/routes/main.py
- app/templates/admin/base/index.html
- app/templates/admin/ticket-transfer-log/ticket-transfer-log.html
acccess ticket transfer log from admin
> Trasnfer log admin

- app/controllers/ticket_transfer_controller.py
#456 
when password did not in payloads :
when password is not match:
when password is match:
this response below like this because i don't know what is receiver
> 456 ticket transfter auth

- app/controllers/speaker_document_controller.py
- app/routes/api.py
- app/services/speaker_document_service.py
#459 
SCREENSHOT :
when logged in as user:
when logged in as speaker:
> 459 speaker document filter

- app/controllers/speaker_document_controller.py
- app/templates/admin/speakers/speaker_document.html
> #458 admin panel upload speaker document

- app/configs/settings.py
- app/controllers/sponsor_controller.py
- app/services/sponsor_service.py
> 462 fix API for new payload (sponsor pic)

- app/services/sponsor_service.py
> 462 fix picture return to become a url

- app/services/sponsor_service.py
> #462 fix url again, this time in show

- app/services/schedule_service.py
#464 
respon might be like this :
> #464 include speaker data to schedule list

- app/services/event_service.py
> #466 Include Participant Data

- app/services/sponsor_service.py
> #473 bug sponsor template

- app/controllers/sponsor_controller.py
- app/models/sponsor.py
- app/services/sponsor_service.py
- app/templates/admin/partnership/sponsors/sponsors.html
- app/templates/admin/partnership/sponsors/sponsors_add.html
- app/templates/admin/partnership/sponsors/sponsors_edit.html
- migrations/versions/e1d00374aede_add_url_and_callback_url.py
add sponsor url and callback url
> add url and callback url to sponsor

- app/configs/settings.py
- app/controllers/order_verification_controller.py
- app/models/order_verification.py
- app/routes/api.py
- app/services/__init__.py
- app/services/order_verification_service.py
- migrations/versions/14bd1c1fb1d2_create_order_verifications_table.py
- migrations/versions/b186f6b143e0_merging_heads_invoice_feeds_package.py
> 479 offline payment verification

- app/configs/constants.py
- app/controllers/order_controller.py
- app/controllers/order_verification_controller.py
- app/controllers/payment_controller.py
- app/models/order_verification.py
- app/models/payment.py
- app/routes/api.py
- app/services/order_service.py
- app/services/order_verification_service.py
- app/services/payment_service.py
- migrations/versions/98ecbda34ad3_add_is_used_to_order_verification_tables.py
- migrations/versions/d40a0bb48635_add_curency_to_payments_table.py
- requirements.txt
> Paypal Payment

- app/configs/constants.py
- app/services/order_service.py
> make paypal setting be constant

- app/services/order_service.py
> 487 fix ticket price

- app/controllers/user_authorization_controller.py
- app/services/user_service.py
> 488 Tweak Registration

- app/configs/settings.py
- app/controllers/ticket_controller.py
- app/models/ticket.py
- app/services/ticket_service.py
- migrations/versions/e24020fea140_add_type_and_proposal_url_to_tickets_.py
#492 
get all ticket, if url none is null
if type == user
if type == exhibition
> 492 ticket type

- app/models/order_verification.py
- app/routes/api.py
- app/services/helper.py
- app/services/order_verification_service.py
- app/services/user_ticket_service.py
- app/static/src/payment_verification/verification-model.js
- app/templates/admin/base/index.html
- app/templates/admin/payment_verification/verification_list.html
> clean some code, and implmentation on admin panel

- app/controllers/ticket_controller.py
- app/services/ticket_service.py
- app/templates/admin/tickets/ticket_add.html
- app/templates/admin/tickets/ticket_edit.html
- app/templates/admin/tickets/tickets.html
> 498 admin panel tweak ticket

- manage.py
- seeders/ticket_tweak_seeder.py
> 493 seeder tweak

- app/configs/constants.py
- app/models/ticket.py
- app/services/order_verification_service.py
- app/services/payment_service.py
- app/services/redeem_code_service.py
- migrations/versions/590e64b96673_add_quota_column_to_tickets_table.py
> 495 tweak become exhibitor

- app/services/user_service.py
> fix referal flasw

- app/configs/constants.py
- app/models/hacker_team.py
- app/models/user_hacker.py
- app/services/order_verification_service.py
- app/services/payment_service.py
- migrations/versions/66237493cf86_create_user_hackers_table.py
- migrations/versions/8d8ba52d1417_create_hacker_teams_table.py
> 510 hackaton team purchase
